### ISSUE TITLE
Running multiple R scripts within lambda?

### ISSUE THREAD

**Issue by gabrielpulga** [mdneuzerling/lambdr#12]
Hello, first of all, let me say **congratulations** for your guys work! I have been tweaking with lambda and R for the past few weeks and with your code I finally managed to make it work - well, a small part of my project at least.

The issue is, your solution is working fine for a small function like `parity` but how would it work for a script that uses a number of libraries along with another script as input?

And also, is there a way to escalate this for a number of scripts? For instance, I have around 40 R scripts and would like to run all of them using lambda.

**Comment by mdneuzerling** [comment]
Hi @gabrielpulga. I'm glad you've found the package useful!

You have a lot of freedom with how to construct the Docker image. Assuming you stick with a `runtime.R` like I have in my examples, the requirement is that your `runtime.R` script loads whatever functions and dependencies you need to run your Lambda. This file could `source` other files or load other packages. Just make sure the files you need and packages you depend on are in the Docker image. Always test your Lambdas locally first — the most common mistakes I make are in the Dockerfile!

For multiple Lambdas, you can make things a bit simpler by sharing the same Docker image and changing the _handler_. For example, I could define `parity1` and `parity2` in my `runtime.R` file. Then, through the AWS console, I can use the same container for two Lambdas, but use different handlers `parity1` and `parity2`. The `lambdr` package will look for a function with the same name as the handler, so the only requirement is that the function defined by the handler exists and can be found. Moreover, the handler set by the AWS console will override everything else.

40 functions is a lot! I'm assuming they're all somewhat related? If so, I'd _strongly_ recommend creating a custom package and installing that into the Docker image. Your `runtime.R` can then simply be `library(CustomPackage)`.

**Comment by gabrielpulga** [comment]
Hey @mdneuzerling ! Thank you so much for your response.

That makes a lot of sense and is actually the way I have been trying to implement my project into lambda.

Could you please elaborate on loading other scripts through the `runtime.R` file?

For instance, I have two scripts : `generate_presentation.R`and `line_plot.R`. The first one depends on the second one, but I only run `generate_presentation.R` to effectively get the output I want.

How do I use these within the `runtime.R` file? I thought about the following pathway, please correct me if I'm wrong (I am still mostly a noob with R) :

Dockerfile lines :
```
# Copy across runtime.R and any other necessary files
RUN mkdir /lambda
COPY /scripts/. /lambda
RUN chmod 755 -R /lambda

# Generate a simple bootstrap which runs runtime.R with R
RUN printf '#!/bin/sh\ncd /lambda\nRscript runtime.R' > /var/runtime/bootstrap \
  && chmod +x /var/runtime/bootstrap

# Set the handler as the CMD. The lambdr package interprets the handler as the name of the function to use, in this case, “parity”. The CMD can also be set (or overriden) when setting up the Lambda in AWS.
CMD ["main"]
```

```
# All scripts are within the same folder in /scripts and being copied into the image
main <- function() {
  source("generate_presentation.R")
}

lambdr::start_lambda()
```
Would something like this work?

**Comment by gabrielpulga** [comment]
Update : the code I've mentioned above worked out! :D

I'm now curious if it will escalate for the other scripts as well and if the best approach is to source all of them in one lambda or if I should divide them into more than one.

**Comment by mdneuzerling** [comment]
I’m glad it works!

You shouldn’t need to wrap the `source` call in a function. When the lamba starts it still run all of the code in the runtime.R file. Putting `source("generate_presentation.R")` at the top of the file should be enough. You can also attach packages this way, eg. “library(dplyr)`, and use any function exported by that package as a handler function.

You can source as many files as you’d like, but I’d caution that at some point complexity will be an issue. If you find yourself sourcing many files it’s a sign that you may want to refactor your project as an R package.
