### ISSUE TITLE
Incorrectly classified SNS events

### ISSUE THREAD

**Issue by hrvg** [mdneuzerling/lambdr#16]
Thanks for this great package!

I noticed when testing locally with a basic container that SNS events are not correctly classified.

I am running the [vignette container](https://lambdr.mdneuzerling.com/articles/lambda-runtime-in-container.html) with the following `runtime.R`:

```
#' Determine if the given integer is even or odd
#'
#' @param number Integer
#' @return "even" or "odd"
#' @examples
#' parity(3) # odd
#' parity(4) # even
parity <- function(number) {
  list(parity = if (as.integer(number) %% 2 == 0) "even" else "odd")
}

#' A nullary function that returns the current version of R
#'
#' @return character
#' @export
#' @examples
#' hello()
hello <- function(...) {
  list(response = paste("Hello from", version$version.string))
}

logger::log_formatter(logger::formatter_paste)
logger::log_threshold(logger::DEBUG)
lambdr::start_lambda()
```

The container is started with `docker run -p 9000:8080 {container-name} "hello"`.

If I pass the EventBridge event from this [vignette](https://lambdr.mdneuzerling.com/articles/eventbridge-and-sns-invocations.html) or AWS Lambda test tab with `curl -X POST "http://localhost:9000/2015-03-31/functions/function/invocations" -d {'payload'}`
```
{
  "id": "cdc73f9d-aea9-11e3-9d5a-835b769c0d9c",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "123456789012",
  "time": "1970-01-01T00:00:00Z",
  "region": "us-east-1",
  "resources": [
    "arn:aws:events:us-east-1:123456789012:rule/ExampleRule"
  ],
  "detail": {}
}
```

The container returns the expected `DEBUG` log: `event class:  eventbridge_event`.

However, both the event from the SNS event from the [vignette](https://lambdr.mdneuzerling.com/articles/eventbridge-and-sns-invocations.html) and AWS Lambda test tab:

```
{
  "Records": [
    {
      "EventSource": "aws:sns",
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:us-east-1:{{{accountId}}}:ExampleTopic",
      "Sns": {
        "Type": "Notification",
        "MessageId": "95df01b4-ee98-5cb9-9903-4c221d41eb5e",
        "TopicArn": "arn:aws:sns:us-east-1:123456789012:ExampleTopic",
        "Subject": "example subject",
        "Message": "example message",
        "Timestamp": "1970-01-01T00:00:00.000Z",
        "SignatureVersion": "1",
        "Signature": "EXAMPLE",
        "SigningCertUrl": "EXAMPLE",
        "UnsubscribeUrl": "EXAMPLE",
        "MessageAttributes": {
          "Test": {
            "Type": "String",
            "Value": "TestString"
          },
          "TestBinary": {
            "Type": "Binary",
            "Value": "TestBinary"
          }
        }
      }
    }
  ]
}
```

return `event class:  event` instead of `event class:  sns_event`.

You can verify that this behavior is abnormal, but I believe the issue is in `is_sns_event_content`:

```
is_sns_event_content <- function(event_content) {
  grepl('"EventSource":"aws:sns"', event_content)
}
```

which should be (adding a space after the colon):

```
is_sns_event_content <- function(event_content) {
  grepl('"EventSource": "aws:sns"', event_content)
}
```

**Comment by mdneuzerling** [comment]
Thanks for this! You can use `remotes::install_github("mdneuzerling/lambdr")` to install the development version with the fix. I'll also work to get this on CRAN.

Apologies for the delay in responding to this.
