### ISSUE TITLE
Question on invocation from cURL command

### ISSUE THREAD

**Issue by mpettis** [mdneuzerling/lambdr#22]
UPDATE: I probably spoke to soon... I believe it is addressed here: https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html

This may not pertain to this project, but to lambdas overall... How do you submit a lambda call to this container from, say, `curl` rather than just with `aws lambda`?

**Comment by mdneuzerling** [comment]
Hi @mpettis, sorry for the delay in responding. I think for this you would need to put [an API Gateway in front of your Lambda](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html). The `lambdr` package does support [invocations to Lambdas that come from API Gateways](https://lambdr.mdneuzerling.com/articles/api-gateway-invocations.html).
