### ISSUE TITLE
yum commands need replacing.

### ISSUE THREAD

**Issue by sebsilas** [mdneuzerling/lambdr#27]
Hi there,

Thanks for this great package.

It seems that `yum` is not working any more (it's being deprecated). Thus your Dockerfile example has stopped building for me. I'm not sure how to update it yet (e.g., with `dnf`). If I figure it out, I will send a PR, but thought I'd like you know in case you want to update it yourself more quickly.

All the best,
Seb

**Comment by mdneuzerling** [comment]
Hi Seb,

Thanks for raising this! I had no idea that `yum` was being deprecated.

I’m travelling at the moment so I won’t be able to look at this right away. If you cannot find a solution over the next week or two I’ll give it a go when I get back.

Regards,
David

**Comment by aavanesy** [comment]
Anyone has a solution to this?

**Comment by sebsilas** [comment]
Yes, sorry. The quick (perhaps hacky) fix is to version the Lambda environment. So place the following at the beginning of the Dockerfile:

`FROM public.ecr.aws/lambda/provided:al2.2023.11.01.17
`

We also struggled to find a way of replacing it (e.g., with dnf).

If anyone else comes up with some other alternatives, I'd be interested to know.

All the best,
Seb

**Comment by aavanesy** [comment]
> `FROM public.ecr.aws/lambda/provided:al2.2023.11.01.17 `
This is actually the best solution.
I have both the R version and the package versions locked in. 
This would be perfect, as I expect my lambda's to run the next 10 years....

**Comment by mdneuzerling** [comment]
I had no idea this package was being used so widely! 

I promise I’ll take a look at this when I return home.

**Comment by sebsilas** [comment]
> I had no idea this package was being used so widely!
> 
> I promise I’ll take a look at this when I return home.

I've used it in both industry and academic settings, it's a very useful package!

**Comment by aavanesy** [comment]
`FROM public.ecr.aws/lambda/provided:al2` worked just perfectly!

**Comment by mdneuzerling** [comment]
For now I'm going to update the docs to include the al2 tag, and also a recommendation that the tag should be changed to a specific version for any production use.

I'm a little bit scared that this is a temporary fix. But if so I'll deal with that when the time comes. I have some idea of how to replace `yum` anyway.
