### ISSUE TITLE
epel 7 no more available breaking docker build

### ISSUE THREAD

**Issue by flochaz** [mdneuzerling/lambdr#38]
# Description

It appears that the Dockerfile instruction to download the EPEL release RPM is failing. The URL https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm is no longer available, causing the build process to fail.

# Steps to Reproduce:

Clone the repository.
Attempt to build the Docker image using the provided AL2 based Dockerfile code given in README
Observe the failure during the step that involves downloading the EPEL release RPM.

# Expected Behavior:
The Docker image should build successfully without any errors related to downloading the EPEL release RPM.

# Actual Behavior:
The build process fails with an error indicating that the URL https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm is not reachable.

# Possible Solution:
Maybe use al2023 instruction from https://github.com/mdneuzerling/lambdr/issues/31 or rocker one : https://github.com/mdneuzerling/lambdr/pull/37

**Comment by mdneuzerling** [comment]
Thank you for the heads up. I think this might be the final nail in the coffin for using Amazon Linux in the examples. It's just far too prone to breaking.

@jimgar has recently updated the Vignettes to include a lot more detail on how to build a Lambda function the popular Rocker images. I will update the README example to use Rocker as well.
